name: Lesson 2 Assignment

on:
    push:
        branches: [main, master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'
            - name: Install dependencies
              run: npm ci
            - name: Print debugging information
              run: |
                echo "Node Version: $(node --version)"
                echo "NPM Version: $(npm --version)"
                echo "Working Dictionary: $(pwd)"
                echo "Contents of Working Directory: $(ls -l)"
                echo "Contents of node_modules: $(ls -l node_modules)"
    test:
      needs: build # build must succeed before testing
      runs-on: ubuntu-latest

      steps: 
          - name: check out code
            uses: actions/checkout@v2

          - name: use Node.js
            uses: actions/setup-node@v2
            with:
              node-version: '20'
          
          - name: Install dependencies
            run: npm ci

          - name: Run Tests
            run: npm test
    deploy:
        needs: test #tests must succeed before deploying
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '20'
        - name: Install Dependencies
          run: npm install
        - name: Install Vercel CLI
          run: npm install --global vercel@latest
        - name: Pull Vercel Environment Information
          run: vercel pull --yes --environment=preview --token=${{ secrets.LESSON2_VERCEL_TOKEN }}
        - name: Build Project Artifacts
          run: vercel build --token=${{ secrets.LESSON2_VERCEL_TOKEN }}
        - name: Deploy Project Artifacts to Vercel
          run: vercel deploy --prebuilt --token=${{ secrets.LESSON2_VERCEL_TOKEN }}